export const STORE_LIST_LOADING = 'STORE_LIST_LOADING';
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS';
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL';

export const FEATURED_LIST_LOADING = 'FEATURED_LIST_LOADING';
export const FEATURED_LIST_SUCCESS = 'FEATURED_LIST_SUCCESS';
export const FEATURED_LIST_FAIL = 'FEATURED_LIST_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_IN_CART = 'INCREMENT_IN_CART';