export const STORE_LIST_LOADING = 'STORE_LIST_LOADING';
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS';
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL';

export const FILTERED_LIST_LOADING = 'FILTERED_LIST_LOADING';
export const FILTERED_LIST_SUCCESS = 'FILTERED_LIST_SUCCESS';
export const FILTERED_LIST_FAIL = 'FILTERED_LIST_FAIL';

export const SINGLE_ITEM_LOADING = 'SINGLE_ITEM_LOADING';
export const SINGLE_ITEM_SUCCESS = 'SINGLE_ITEM_SUCCESS';
export const SINGLE_ITEM_FAIL = 'SINGLE_ITEM_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_CART = 'INCREMENT_CART';
export const DECREMENT_CART = 'DECREMENT_CART';